### ISSUE TITLE
Internal Web Browser not working

### ISSUE THREAD

**Issue by lesaber** [angelozerr/angular-eclipse#100]
When I "Run As" -> "5 ng serve"  the page does not display.  If I use an external browser like chrome and point to localhost:4200 it displays properly. If I use a different URL in the internal eclipse browser it displays properly.

Angular2 Eclipse 1.4.0.201707100742 angular2-feature.feature.group Angelo ZERR

Eclipse Java EE IDE for Web Developers.
Version: Oxygen Release (4.7.0)
Build id: 20170620-1800

**Comment by angelozerr** [comment]
When Run as > ng serve is executed, it tracks terminal trace to find the URL to open. I think the URL to open is done beforiowe that server is started. If you do a refresh of your Internal Web Browser is it working?

To be honnest with you, if there are problem with Internal Web Browser, I could not fix it. It belongs to Eclipse JEE

**Comment by lesaber** [comment]
Refresh of internal browser does not resolve the issue.

**Comment by Springrbua** [comment]
@lesaber in your Eclipse preferences you can choose which webbrowser to open by default.  
I suggest you to choose an external borwser (like Chrome) there. It would be much better to debug and test your application. The Eclipse internal Browser is probably pretty minimal, so I don't think it is the right one to use here.

**Comment by angelozerr** [comment]
This issue is not an angular eclipse issue but an Eclipse issue. @lesaber if you have again problem, please submit your bug to eclipse. Thanks!
