### ISSUE TITLE
Rethink releases and update site

### ISSUE THREAD

**Issue by probert94** [angelozerr/angular-eclipse#102]
The newest stable version of the plugin (1.3.0) is in my opinion a pretty complete and stable version.  
However there is a bug with the angular project wizard, which has been fixed in the 1.4.0 Snapshot (One PR still open).  
I would like to be able to add bugfixes like this to a Version 1.3.1 or something like this.  
This new version should be downloadable on the same update site (http://oss.opensagres.fr/angular2-eclipse/1.3.0/).
Also it would be cool to have a URL for `latest stable` and for `latest snapshot`.  
With this changes a user does not need to manually change the update site everytime a new version is released.  
@angelozerr @pascalleclercq what to you think about this?

**Comment by rubensa** [comment]
If you want to use same update site for a minor **version and It's bug-fixes**, It's URL shouldn't be like:

_http://oss.opensagres.fr/angular2-eclipse/1.3.x/_

o simply:

_http://oss.opensagres.fr/angular2-eclipse/1.3/_

to avoid confusion (as 1.3.0 denotes the "**exact**" 1.3.0 version)?

**NOTE**: +1 to a `latest stable` and `latest snapshot` URL.

**Comment by Springrbua** [comment]
@rubensa yea you are right it the URL shouldn't contain the exact version number but only the first two parts (currently 1.3).

**Comment by angelozerr** [comment]
I agree with you but our problem is time. Not sur that pascal could find time to manage that.

**Comment by pascalleclercq** [comment]
I agree too.

Will manage It ASAP/

**Comment by pascalleclercq** [comment]
And voilà : http://oss.opensagres.fr/angularjs-eclipse/snapshot/

might be latest-snapshot but I prefer to avoid whitespace.

Let's test http://oss.opensagres.fr/angularjs-eclipse/stable/ during the next release ?

**Comment by Springrbua** [comment]
@pascalleclercq That was fast, but isn't that the wrong plugin? The update-site points to `angularjs-eclipse`, while this one is angular-eclipse.

**Comment by angelozerr** [comment]
@pascalleclercq I'm changing step by step Angular2 to Angular.

I have changed the github url and some label, we need to change too feature etc. So it should be cool if we coulf have 

  * http://oss.opensagres.fr/angular-eclipse/snapshot/
 * http://oss.opensagres.fr/angular-eclipse/stable/

**Comment by pascalleclercq** [comment]
http://oss.opensagres.fr/angular-eclipse/
and voilà...

Please pull before doing anything.

I didn't refactored the package names yet. IMHO @angelozerr  should do It.

**Comment by angelozerr** [comment]
> I didn't refactored the package names yet. IMHO @angelozerr should do It.

@pascalleclercq  thanks a lot for your work! I have updated classes, packages from "angular2" to "angular".

@Springrbua pay attention the project name have changed.

**Comment by Springrbua** [comment]
@angelozerr Thanks for the information. So I probably have to reimport the project(s) right?
