### ISSUE TITLE
HTML Editor shows Typescript errors

### ISSUE THREAD

**Issue by gdj1975** [angelozerr/angular-eclipse#105]
On eclipse oxygen the html editor shows typescript compile errors on html files. I think html files should not be validated with typescript compiler. 

Affected versions:
- angular-eclipse 1.3.0

Steps to reproduce:
1. create a new angular project
2. create a new component
3. open the html file of the new component

Is there a workaround to get rid of the compile errors?

**Comment by gdj1975** [comment]
Attached screenshot.

![screenshot](https://user-images.githubusercontent.com/30720473/28962628-8ebc7da6-7906-11e7-8bef-a9dff8d96a3a.jpg)

**Comment by angelozerr** [comment]
Same issue than https://github.com/angelozerr/angular-eclipse/issues/97

> Is there a workaround to get rid of the compile errors?

For the moment you must fix at hand tsserver.js https://github.com/angelozerr/angular-eclipse/issues/97#issuecomment-314683721 by waiting fix of TypeScript tsserver https://github.com/angelozerr/angular-eclipse/issues/97#issuecomment-319022466

**Comment by azakrytnoi** [comment]
Issue closed, but bug is still present.
When the real fix or workaround will be available?

**Comment by angelozerr** [comment]
I'm waiting for that TypeScript tsserver implement this feature, for the moment I have not seen something...
