### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by jacopolanzoni** [angelozerr/angular-eclipse#108]
I have got a macOS Sierra Version 10.12.6 and Eclipse IDE for Java Developers Mars.2 Release (4.5.2). Moreover, I have got installed node v6.9.2, npm 5.3.0 and angular-cli 1.0.0-beta.28.3. I installed Angular IDE 2017 CI 6a from Eclipse Marketplace but I don't see any Angular project between my options for a New project. I have tried to uninstall and install again many times, and checked that I installed the package with all the selected features (see attached screenshot)
![confirmselectedfeatures](https://user-images.githubusercontent.com/5550364/29242981-f1cf157a-7f8c-11e7-9749-fc4a59ba5f60.png)
 but no luck. I am sure I am missing some basic step but I cannot figure out which one. Any help?

**Comment by angelozerr** [comment]
I close this issue because it's not an issue of Angular Eclipse but an issue of Angular IDE which is an another plugin.

If you wish to install Angular Eclipse, please read https://github.com/angelozerr/angular-eclipse/wiki/Installation-Update-Site
