### ISSUE TITLE
Angular template editor doesn't work on linux

### ISSUE THREAD

**Issue by igorlash** [angelozerr/angular-eclipse#109]
I have created two identical application on windows 10 

![new_project_win](https://user-images.githubusercontent.com/31065075/29358483-e104db40-8283-11e7-8b5e-7090cf9568b5.png)

and linux mint 18.2

![new_project_linux](https://user-images.githubusercontent.com/31065075/29358484-e1101abe-8283-11e7-9c03-c70ca4d28968.png)

When I open a generated angular template on windows everything is ok

![template_win](https://user-images.githubusercontent.com/31065075/29358591-3bb81d36-8284-11e7-8362-235b47171f26.png)

but on linux every line is marked as errors containing 
![template_linux](https://user-images.githubusercontent.com/31065075/29358669-80d87ed8-8284-11e7-859b-28d54ebc4b96.png)

and code completion is not functioning. 

The same eclipse packages were used on both operation systems 

- linux - eclipse-javascript-oxygen-R-linux-gtk-x86_64.tar.gz
- windows - eclipse-javascript-oxygen-R-win32-x86_64.zip

**Comment by angelozerr** [comment]
I think you can have the same problem with windows (it depends on which file you hav eopened the first time, but not sure with that). 

Your issue is the same than https://github.com/angelozerr/angular-eclipse/issues/97 

We must be patient https://github.com/angelozerr/angular-eclipse/issues/97#issuecomment-319022466

**Comment by igorlash** [comment]
I think you are right. I have just rechecked. If after creating a new project,  **.angular-cli.json** is opened first, then the template editor works well.

**Comment by angelozerr** [comment]
I close this issue in favor to https://github.com/angelozerr/angular-eclipse/issues/97
