### ISSUE TITLE
Add to workspace Angular Project downloaded from repository

### ISSUE THREAD

**Issue by tokiaquino** [angelozerr/angular-eclipse#113]
I created project from scratch without problem, but when i want import a project the wizard doesn't find the `@angular/cli`

**Comment by angelozerr** [comment]
Please share your project.

**Comment by tokiaquino** [comment]
It's a private project create by my partner from terminal with ng command, and hes using sublime for coding

**Comment by Springrbua** [comment]
I imported a few projects without problems.  
Here is what I did:  
1) File -> New Project -> Select "General/Project".  
2) Select the Root-Dir of the project (containing the .angular-cli.json)  
3) Open terminal and run npm install, to install all needed dependencies (including angular-cli)  
4) Open project preferences and select the cli-installation. The combo-box should already contain one default value, which should work. It points to the project-local location.

**Comment by tokiaquino** [comment]
Ok, then the trick is create a "General Project" and not an "Angular Project".
Then run **npm install** on terminal, and it works like a charm

Thanks

**Comment by angelozerr** [comment]
@Springrbua thanks for your help!

@tokiaquino can we close this issue?

**Comment by tokiaquino** [comment]
@angelozerr  Totally
