### ISSUE TITLE
Getting started is not enough

### ISSUE THREAD

**Issue by ronatartifact** [angelozerr/angular-eclipse#126]
I just installed Angular Eclipse 1.4.0.201807261042 but I can not create a new project.
I suspect that there is some setup that has to be done in Eclipse preferences to tell it where Angular is installed. Am I right and what needs to be done to tell the plug-in where the software is?
I am on CentOS 7 running Eclipse Spring Tool Suite 

Version: 3.9.5.RELEASE
Build Id: 201807031753
Platform: Eclipse Photon (4.8.0)
npm--version shows 
  npm 6.4.1 
ng --version shows 
Node: 10.13.0
OS: linux x64
Angular: 7.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.5
@angular-devkit/build-angular     0.10.5
@angular-devkit/build-optimizer   0.10.5
@angular-devkit/build-webpack     0.10.5
@angular-devkit/core              7.0.5
@angular-devkit/schematics        7.0.5
@angular/cli                      7.0.5
@ngtools/webpack                  7.0.5
@schematics/angular               7.0.5
@schematics/update                0.10.5
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

Do  I need to tell Eclipse about any of this?
When I try to start a new project I see a message "Searching for global Angular CLI in global preferences..." and can not finish the creation.

**Comment by angelozerr** [comment]
I must find time to retry this feature with new Angular version.

@Springrbua is there any chance that you help @ronatartifact ?

**Comment by probert94** [comment]
The Angular CLI changed quite a bit since we last worked on the plugin. Chances are, that it isn't compatible anymore...
To be honest, I suggest to use only the Typescript plugin and use the command line (or the new "Angular Console") for CLI related things.
Most people are using vs code for angular development and there is no UI for the Angular CLI.

**Comment by ronatartifact** [comment]
Yes. I have Angular7 and the latest Spring STS.3.9.5.

I am just starting to learn Angular and Typescript so I will be a good 
test case about the clarity of the interface.
I have been using Spring, Java and STS for more than 10 years and am 
still learning how to do it right.

If the user can do something silly and break something, I will likely 
find it!

I am running on the latest CentOS7 with a 16 Gb of memory and an SSD 
drive so I may not be the best judge of speed.


Ron

**Comment by ronatartifact** [comment]
It looks like Springrbua is correct and the plug-in is no longer compatible.
Back to the command line!
