### ISSUE TITLE
Integrate code completion and validation in Html editor for SCSS classes 

### ISSUE THREAD

**Issue by cvgaviao** [angelozerr/angular-eclipse#87]
When I create a angular 2 project using SCSS style, the Http editor showed me lot of warning about  "Undefined CSS class".
Would be great this plugin to read from .angular-cli.json the location of the used style files and use them to propose code completion and validation.

**Comment by angelozerr** [comment]
I think you are using WTP WebResources https://github.com/angelozerr/eclipse-wtp-webresources

This plugin should provide an extension to support that, but to be honnest with you, no time for the moment to do that.

**Comment by angelozerr** [comment]
This issue is not for angular project but for  https://github.com/angelozerr/eclipse-wtp-webresources
