### ISSUE TITLE
Angular Project creation wizard does not honor preferences

### ISSUE THREAD

**Issue by rubensa** [angelozerr/angular-eclipse#98]
In New Angular Project wizard I selected:
**Node.js** : Use embedded
**Angular CLI**: Install @Angular/cli@1.2.0
In Next page:
**Style**: scss
Checked **Routing**

In Terminal the command executed:
 * `npm install @angular/cli@1.2.0`
 * `export PATH=/home/rubensa/development/eclipse/4.7.0_base/workspace/.metadata/.plugins/ts.eclipse.ide.server.nodejs.embed.linux.gtk.x86_64/node-v6.9.4-linux-x64/bin:/home/rubensa/development/eclipse/4.7.0_base/workspace/prueba2/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
 * `ng new prueba2 -dir ./`
 * `npm install tslint-language-service`

**Note**:  no **--routing --style scss** options specified in **ng** command.

**Comment by angelozerr** [comment]
@Springrbua could you see this problem? Thanks!

**Comment by Springrbua** [comment]
I'll take a look at it. Thanks for the information!

**Comment by Springrbua** [comment]
@rubensa Thanks for reporting this Issue. I am pretty sure, that I tested it before, but I was using Eclipse Neon. Now that I am on Oxygen I have the same Issue as you. Are you using Oxygen too?  
If thats the case, they probably changed something in Oxygen, which causes this Issue.  
However it should be fixed as soon as the PR gets merged :)
Thank you

**Comment by rubensa** [comment]
Hello @Springrbua 
Yes, I started with Neon but now I'm on Oxygen (try debugging features -not yet tried-).
I'll try your fix.

Thans!

**Comment by rubensa** [comment]
@Springrbua 

Just checked from http://oss.opensagres.fr/angular2-eclipse/1.4.0-SNAPSHOT/ version.

Same test case as first comment.

**Style** combo preference seems to be honored.
**Routing** check box seems **NOT** to be honored.

Command executed in Terminal:
`ng new demo3 --style scss -dir ./`

**Note**: no **--routing** option specified in **ng** command.

Tested with other check-box preferences (checked) and seems that are not honored.  
The fix seems to only fix the combo-box preference.

**NOTE**:  @angelozerr  Should I open a new Issue or can this one be reopened?

**Comment by Springrbua** [comment]
@rubensa Thanks for the information. I just tested it again with Eclipse Neon, and it seems to happen there too.  
Somehow the Event does not contain the `Widget` it occured on.  
Hopefully I'll find some time tonight to fix and test it. Yesterday I only did a quick test and it worked. I probably changed the combobox only...  
Sorry for that

**Comment by Springrbua** [comment]
@rubensa This should be fixes as soon as #101 gets merged.  
Thank you very much for your patience :)

**Comment by rubensa** [comment]
@Springrbua Thank you for fixing.

I'll try it when merged and propagated to Update Site.

**Comment by rubensa** [comment]
Helo @Springrbua 

Installed and checked new version.  All seems fine now.

Thanks!

**Comment by Springrbua** [comment]
Thank you very much for testing :)
